### ISSUE TITLE
Add new Knowledge-related attributes to AutomationIssue

### ISSUE THREAD

**Issue by i-kushlianski** [arago/OGIT#464] opened 2019-06-27 11:14 UTC
Please take a look at the following Pivotal task https://www.pivotaltracker.com/story/show/166905125

We need to add three more attributes to AutomationIssue to implement issue and session fetching for ATQ, KAT and other apps.

Fields to be added:
```
"ogit/Knowledge/Status"?: IssueStatus,
"ogit/Knowledge/Progress"?: number,
"ogit/Knowledge/Owner"?: string
```

```
type IssueStatus =
  | "started" // A SME has begun teaching/opened issue in KAT
  | "handedover" // A SME has finished teaching, and clicked handover button
  | "converting" // A AIE has started conversion/opened issue in KAT
  | "deployed"; // A AIE has deployed all KIs
```

This was discussed with Dominic Cassidy (@Drache93).

**Comment by cy303** [comment] 2019-06-27 11:35
I have also discussed this topic extensivly with Dominic the last two days and actually the problem needs to be reviewed from a different perspective as some basic assumptions on the workflow are flawed. Storing teaching session related information inside of the issue is a bandaid that would only solve performance issues for a conceptual problem that would not go away by adding this.

**Comment by miraage** [comment] 2019-06-27 11:49
@cy303 in this particular case, our domain model is an Issue. We need to fetch a list of filtered paginated issues. Since issue vertices in the graph are not having a common parent/root, we can not use gremlin query to receive the list. 
That's why we want to store those defined attributes (so they don't turn into issue variables).
Otherwise we need to write extremely inefficient code which will run multiple lucene/gremlin queries in order to show a list of 10 issues with some extra data.
What would you suggest us in such case?

**Comment by cy303** [comment] 2019-06-27 12:06
@miraage to not mess up a semantic data model just for performance reasons if the underlying usecase is flawed and needs fixing anyways ;) joking aside, my current understanding is that the whole reason why this is a performance problem is that the use case has not been properly thought through and adding stuff to ogit should be considered a permanent change, so until I further discussed this with PM feel free to use undefined attributes here OR use inefficient gremlin queries but do not add attributes to issues that semantically really do not belong there

**Comment by Drache93** [comment] 2019-06-27 13:48
@i-kushlianski We'll leave this for now while we examine other long term solutions.

**Comment by miraage** [comment] 2019-07-01 09:02
We can close this issue in light of our recent idea to use another vertex for such purpose

**Closed** 2019-07-01 13:03 UTC
